### ISSUE TITLE
TODO-tracking for Amnesty

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1042]
This ticket is to keep the TODO-list tracking for Amnesty
GLOBALEAKS UX REVIEW hours 16.30 4th Dec 2014:

SETUP
Remove Setup 1/3:
- [x]  Change it to “Select Language”
- [x] Make it click the entire language button (not just the radio button)

Language selector
- [x]  - Make the boxes all clickable
- [x]  - When clicked should grey out

Share Information:
- [x] - Remove the disclaimer (to be confirmed)
- [x] - Add amnesty statement

Receipt page:
- [x] - If the user click the Amlea Logo, the user should be back to the submission page (without going trough the Language selection modal dialog)
- [x] - If the user insert a new Receipt, he must log-in back
- [x] - Remove the "dash" among the various number, but "spaces"
- [x] - Change the background colour of the box displaying the receipt to the UX/Yellow one
- [x] - Add Yellow alert bar at the top of receipt page displays instructions of how to close Tor: "To finish this session,  simply close/ quit the Tor browser" 
- [x] Unless it is less than a week until the ticket expires and then the alert box displays "IMPORTANT: This submission will expire in 8 days."

Tip page:
- [x]  Add Yellow alert bar at the top of receipt page displays instructions of how to close Tor: "To finish this session,  simply close/ quit the Tor browser"
- [x] Unless it is less than a week until the ticket expires and then the alert box displays "IMPORTANT: This submission will expire in 8 days."
- [x] Add "Secure in Tor" header 
- [x] Rework the Privacy Badge by integrating the elements described above
- [x] Add "Status: read/unread" instead of Access Counter
- [x] Adjust the interface not to display the submission fields
- [x] Adjust the interface to display submission field of type "message" as a first comment
- [x] Add the new Downloaded file list
- [x] Add the new Download file functionality

Footer:
- [x]  - Fix the footer to be the one of Amnesty Mockups

Receipt Field Form:
- [x]  - Display spaces among slots of 4 numbers
- [x]  - Enable copy/paste of receive into the Receipt form (filter out spaces and dashes, while being copied)
##

**Comment by fpietrosanti** [comment]
LANGUAGE SELECTION BOX:
* [] It does not highlight the background of selected box
* [] It switch right-to-left when clicking Urdu and Arabic (but it’s expect not to switch)
* [] When switched right-to-left, the button to go-next does not switch right-to-left 
* [] It does not show the step number (1/3 2/3 3/3)
* [] Button say “Proceed” and not “Continue”
* [] Button is not “blue-colored with white text”
* [] on 2/2 Be Secure: the “recommended security advice” is not clickable:
  (it should go to for EN to https://XXX.org/en/#post-22 for AR to https://XXX.org/#post-111 and for UR to https://XXX.org/ur/#post-70 )

FOOTER:
* [] Security Best Practice is not clickable:
  it should go to for EN to https://XXX.org/en/#post-22 for AR to https://XXX.org/#post-111 and for UR to https://XXX.org/ur/#post-70 )

**Comment by evilaliv3** [comment]
this activity tracking is not needed anymore and the project took slightly different directions.
