### ISSUE TITLE
Implement Profile based configuration

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2039]
This ticket is to discuss an collect the requirements fro the implementation of a Profile based configuration.

For what collected so far profiles should:
- Allow the user to pick up a Profile during the wizard (primary)
- Allow the user to pick up a Profile during a later stage of customization (secondary)
- Allow the user to customize the Profile (secondary)
- In case of customized Profiles the platforms should allow manual reset by the a more up-to-date version of a full profile or its individual subcomponent.

To be defined is the content of the profiles, that i expect to be preconfigurations of the default settings:
- default node configurations (intended as recipients configurations, context configurations, notification configurations)
- questionnaires / questions loaded

A proper db structure should be discussed and defined in order to host at least the primary requirements and allowing extensions towards the secondary requirements.

**Comment by evilaliv3** [comment]
With a recent discussion it has been identified to simplify this initial implementation to the load of the Config table, involving a simple load/export of key value pairs.

Specifically it has been also consider to left out of the implementation:
- configuration of contexts: e.g. creation of multiple contexts with different configurations
- configuration of users: e.g. creation of multiple users with different configurations

**Comment by NSkelsey** [comment]
To support a public version of the configuration that describes the loaded profile we would need:

- A single JSON description of that profile.
- The ability to POST that JSON to store/apply/load that profile
- A format for the profile makes no bare references to UUIDs and interprets a map of `"name" => "key"`
- Must be versioned and updatable

Helps us keep tighter control over nodes that are using a specific type of configuration. Up to user to choose to update to the new current default with a big "RESET DEFAULTS" button.

In order to Explain to users the changes to a profile, changelog entries, a paragraph, and maybe even a logo could describe it. All of this could be displayed in the wizard UI.

**Comment by NSkelsey** [comment]
An example profile could be Civil Society Activism:

```
{
   "contexts:" [{
     "name": 'public-campaign",
     'title': 'Report pollution and illegal dumping in the river Po',
     'tip_timetolive': 90,
     'enable_: true,
     'attached_questionaires': ['action-requested', 'types-of-pollutants'],
  }],
  "questionnaires": [
    {'name': 'action-requested', 'steps': 3, 'field-groups': {'.....'}, 
  ]},
  "key": {
    'public-campaign': 'ecd3a0fc-bc6a-400e-875c-5dd8e5ab8869',
    'action-requested': '0c2b6b14-71c4-4d50-92e0-cd9cf44a52e9',
    'types-of-pollutants': 'eeee3f03-dd94-4c96-b081-9e599647433d',
  },
}
```

I really think we will be alright using this. The parsers that are going to have to assert the JSON fields are corrent are going to have to work on this one.

**Comment by NSkelsey** [comment]
In order to implement this feature in `devel` this is roughly what is needed.
**Todo**

- [ ] Adjustment of wizard API endpoint to accept further structured JSON
- [ ] Implement `config` sanitization and assignment
- [ ] Implement needed DB and parsing changes to handle Key-UUID maps
- [ ] Implement `context` cleaning and storage
- [ ] Implement `questionnaire` cleaning and storage
- [ ] Implement UI changes in wizard with profile selection.
- [ ] Update E2E tests to select profile in wizard and to check vars in the initialized backend.

**Comment by evilaliv3** [comment]
@NSkelsey: i've added some revisions on the plan and reordered so that each of the items could be integrated and tested opening the both of us to work on the next steps.

I've removed two items that should not be condisered in this topic:
- contexts: a profile is not intended to load contexts but just to set the configuration for the context generated during the wizard; i dont know if you already considered this but i let you notice that the simple configuration of the defaults values of Config determine the configuration of this context.
- questionnaires: questionnaires import and export are part of https://github.com/globaleaks/GlobaLeaks/issues/2042 that will be a subsequent ticket we will start after this one. In the profile we will for the moment just configure the key of the Default questionnaire; check the 4th item above

**Comment by NSkelsey** [comment]
Ok, I totally agree on the simplification of the questionnaire in this case. The specification of the context likewise could work.

**Comment by NSkelsey** [comment]
This is the basic interface for the feature.

![config-profiles](https://user-images.githubusercontent.com/1095794/29063774-3b167ca0-7c27-11e7-8e51-762459ebc687.png)

There are now two new questions to answer. What are the first profiles we ship and what settings do they flip?
The learn more link will point to a page in the documentation that will describe the various settings each profile throws. In previous revisions of the UI each profile had its own link (which can be brought back). That link can provide a detailed explanation of what settings get enabled.
