### ISSUE TITLE
Issue unique auth tokens for wizard setup and password recovery

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#2040]
As part of the multitenancy phase-in, globaleaks needs a mechanism to issue a user a private way to configure the platform. In general, the platform is also missing the ability to issue expiring, single sign-on tokens to users that have lost passwords and generally become locked out. The implementations of these two things will use and reuse lots of the same code. So I propose working on the two together and ensuring that they are released in conjuction before the v2.80 multitenancy milestone.

Issuing access to the platform via the wizard is quite straight forward:
1) Initialize DB, issue user-auth-token
1) Print token to console at startup
2) User connects to URL over Tor onion service (here there is the possibility to connect over HTTP)
4) Platform checks token, allows config

Reissuing access to a user is similar:
1) Admin selects reset user password
2) Backend provides the frontend with a reset password link with issued token
ex: `https://p1.globaleaks.org/#/wizard?token=51a2493ead1234aeb12e139a31e05`
3) Admin is given responsibility to pass link to user
4) User connects via url, changes password and token is deleted.

**Expected behavior**

Password recovery should be robust and well thought out. This is a proposed solution for #113

**Comment by evilaliv3** [comment]
Good to go for me.
 
Few small revisions:
- the reset token should not be designed to be shown on the interface but shoulld just be mailed to the configured email with a proper reset template; the same should be done at the creation of the user with proper different template; on this second case upon user creation the administrator should be given the possibility deselecting a preselected checkbox to not send the email.
- click on a link with the user reset token should acts as a special authentication leading the user to a page where the user could just reset the password and only after that find themeselves already logged in.

**Comment by NSkelsey** [comment]
**Implementation steps**
- [ ] Add expiring token to DB schema
- [ ] Implement new API to issue and revoke expired token 
- [ ] (maybe) mail user with API token to connect. (links with use and delete)
- [ ] 

**Some notes**
We are going to have to robustly log API token requests and issuance. It will be overkill to build custom UI to display their usage, but it should be clear that someone evil running around with the reset PW token of a user on GL is a catastrophic failure. So we should never be generating more than one of these at a time for each user.

**Comment by evilaliv3** [comment]
Let's discuss a bit on this to keep the implementation simple; keeping it simple is fundamental for multiple reasons here.

I propose this simplified strategy; Let's discuss it a bit on this to keep the implementation simple; keeping it simple is fundamental for multiple reasons here.

I think that:
- The user token could be a raw in the User table; if different an empty string it will host a valid token that will be removed on use.
- The wizard token could be a raw in the User table; if different an empty string it will host a valid token that will be removed on use.

Both this two implementations that just require the additions of two fields in two tables obtain satisfy the security and solve all the previously discussed issues.

**Comment by NSkelsey** [comment]
Sure, we can add the token to the User table. Adding `token_issue_date` as well can solve the token expiration challenge.

Storing the wizard token in the user table will not work, because there is no user on the system before the wizard is configured.

**Comment by evilaliv3** [comment]
Yes definitely

The wizard token was intended to be stored in the Config table.

Good just for the User token to have an expiration date.

**Comment by evilaliv3** [comment]
Deprecated in favor of https://github.com/globaleaks/GlobaLeaks/issues/2043 and https://github.com/globaleaks/GlobaLeaks/issues/113
