### ISSUE TITLE
Implement support for the import and the export of questionnaires

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#2042]
**Current behavior**

Currently every questionnaire created by an Administrator has to be done by scratch, maybe referring to the work someone has done on their project. Note, this is probably a duplicate ticket, but the original has either disappeared, been moved, or been resolved.

**Expected behavior**

The goal of allowing importing questionnaires is to allow the project to refine a few well made internationalized questionnaires that have proven to be successful for specific projects and provide them as pre loaded options new projects can use.

Those questionnaire's uploaded must:
- Have human understandable descriptions
- Be versioned
- Be fully defined in JSON and exported pretty printed!!!!
- Be internationalized
- Handle mapping references from JSON into the primary keys of the field tables
- Be upgradeable

**What is the Use case for changing the behavior?**

The goal is to help an organization like [Transparency International Italia](https://www.transparency.it/) take their anti-corruption work and generalize it for other countries. Further, this is funded work under OTF-2017-3.1.

**Todo**

To build out this functionality we need to accomplish the following in some order.

- [x] Define an import/export format
- [x] Write the exporter with test cases
- [x] Write the importer
- [x] Write the updater
- [x] Change the questionnaire interface
- [x] Change the questionnaire API endpoints
- [x] Internationalize the UI

**Comment by evilaliv3** [comment]
@NSkelsey few notes on some details already implemented in the software;

Various of the things you discussed are in the real already implemented,  let's have a brainstorming together around this topic on Monday so to discuss what we have and move it forward :)

For example:
- the import/export has been already defined for what relates Questions; we will extend this format with a wrapping but similar structure.
- the existing implementations that already load and update the ```whistleblower_identity``` field already keep track of the internationalization needs; you find an example here: https://github.com/globaleaks/GlobaLeaks/blob/master/client/app/data_src/fields/whistleblower_identity.json; you will notice that this ffile contains only english but automagically the build script is able to create the file containing all the languages that is shipped and used into the relese.
- At the same time the file already take care of the update of the field that at every release is injected in the platform updated. What is missing on this topic is just versioning that is something that i continue to suggest to add on a later stage; for now it could just be a variable ```version``` inside the defined jsons but let's not consider it for the moment.

**Comment by NSkelsey** [comment]
Okay, the question import/export is defined and I am fine with letting versioning disappear from the first implementation. Lets at least add a tag to the JSON like `version: '1.0.1'`. 

Finally, we need to update slightly the implementation of whistleblower_identity to not use UUIDs

**Comment by evilaliv3** [comment]
Sure.

Consider that the uuid that you see in the field are already not used when
the field is recreated at update time.

The trick for the replacement is in the 'key' field that is necessary for
mapping a field on an eventual feature. Probably questionnaires will
require this as well.

Let's look at this in detail on Monday to have a good brainstorming on what
existing and what to be done

On Aug 4, 2017 10:36, "Nick Skelsey" <notifications@github.com> wrote:

Okay, the question import/export is defined and I am fine with letting
versioning disappear from the first implementation. Lets at least add a tag
to the JSON like version: '1.0.1'.

Finally, we need to update slightly the implementation of
whistleblower_identity to not use UUIDs

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/globaleaks/GlobaLeaks/issues/2042#issuecomment-320191708>,
or mute the thread

**Comment by NSkelsey** [comment]
8e4c2ca and its corresponding branch `feature/2042` does not contain pretty_printed export, nor does it have a solution for pushing the `id`s of fieldattrs or fieldoptions. This second point is only an issue if we are worried about updating existing loaded questionnaires.

Further the creation of all `Field`s is done with `instance` and `reference` and not as a `template`

**Comment by NSkelsey** [comment]
As a result of keeping the UI very limited -- two new buttons -- the internationalization is essentially complete.

**Comment by NSkelsey** [comment]
This has been released in v2.72.0.
